//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Ccf.Ck.Models.NodeSet
{
    public abstract partial class ActionBase
    {
        public ActionBase()
        {
        }

        public string File
        {
            get;
            set;
        }

        public string LoadQuery
        {
            get;
            set;
        }

        public string Query
        {
            get;
            set;
        }

        public Dictionary<string, object> Json
        {
            get;
            set;
        }
    }
}