//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Ccf.Ck.Models.NodeSet
{
    public partial class CustomPlugin : INode
    {
        public string CustomPluginName
        {
            get;
            set;
        }

        public string AssemblyName
        {
            get;
            set;
        }

        public string ClassName
        {
            get;
            set;
        }

        public string PluginConfiguration
        {
            get;
            set;
        }

        public int Executionorder
        {
            get;
            set;
        }

        public bool BeforeNodeAction
        {
            get;
            set;
        }

        public bool AfterNodeAction
        {
            get;
            set;
        }

        public bool AfterNodeChildren
        {
            get;
            set;
        }
    }
}