//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Ccf.Ck.Models.NodeSet
{
    public partial class Select : ActionBase
    {
#region Private Fields
        private Dictionary<string, object> _Json;
#endregion
#region Public Properties
        public Dictionary<string, object> Json
        {
            get
            {
                return _Json;
            }

            set
            {
                _Json = value;
            }
        }
#endregion
    }
}