//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Ccf.Ck.Models.NodeSet
{
    public partial class Write : OperationBase
    {
        public Insert Insert
        {
            get;
            set;
        }

        public Update Update
        {
            get;
            set;
        }

        public Delete Delete
        {
            get;
            set;
        }
    }
}