//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Ccf.Ck.Models.NodeSet
{
    public partial class NodeSet
    {
        public NodeSet()
        {
            Parameters = new List<Parameter>();
        }

        public Node Root
        {
            get;
            set;
        }

        public List<Parameter> Parameters
        {
            get;
            set;
        }

        public bool RequireAuthentication
        {
            get;
            set;
        }

        public string DataPluginName
        {
            get;
            set;
        }

        public string Name
        {
            get;
            set;
        }
    }
}